name: Signal API Receiver
version: "0.1.0"
slug: signal_api_receiver

description: >-
  Receives Signal messages from signal-cli-rest-api and exposes them
  through a REST API for Home Assistant.

url: https://github.com/kalbasit/signal-api-receiver

arch:
  - amd64
  - aarch64

startup: application
boot: auto
init: false

ports:
  8105/tcp: 8105

ports_description:
  8105/tcp: Signal API Receiver REST API

options:
  signal_account: null
  signal_api_url: null

  log_level: info
  server_addr: ":8105"
  repeat_last_message: false

  mqtt_server: ""
  mqtt_user: ""
  mqtt_password: ""
  mqtt_client_id: ""
  mqtt_topic_prefix: "signal-api-receiver"
  mqtt_qos: 0
  mqtt_retain: false
  mqtt_insecure_skip_verify: false

schema:
  signal_account: str
  signal_api_url: url

  log_level: list(trace|debug|info|warn|error)
  server_addr: str
  repeat_last_message: bool

  mqtt_server: str?
  mqtt_user: str?
  mqtt_password: password?
  mqtt_client_id: str?
  mqtt_topic_prefix: str?
  mqtt_qos: int(0,2)
  mqtt_retain: bool
  mqtt_insecure_skip_verify: bool

apparmor: true