name: "Signal API Receiver"
description: "Bridge between Signal-CLI WebSocket and Home Assistant"
version: "0.0.1"
slug: "signal_api_receiver"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  signal_account: "+49123456789"
  signal_api_url: "ws://192.168.178.10:8080"
  log_level: "info"
  service_port: 8105
schema:
  signal_account: str
  signal_api_url: str
  log_level: str
  service_port: int